from ytdriver import YTDriver, Video, VideoUnavailableException
# from YTDriver_local import YTDriver
# from helpers import Video, VideoUnavailableException
import sys
import json
import time
from datetime import datetime
import os
from random import choice
import pandas as pd
import time
import random
import logging

puppet = {}


def parse_args():
    # Read json sock puppet arguments file generated by docker-api.py
    with open(sys.argv[1]) as f:
        return json.load(f)


def init_puppet(puppetId, profile_dir):
    """
    Creates a new puppet object with:
    1. A YouTube driver (browser automation)
    2. A unique ID
    3. Empty actions list to track what happens
    4. Start time to track duration
    """
    global puppet
    puppet = dict(
        # driver=YTDriver(verbose=True, profile_dir=profile_dir),#, use_virtual_display=True),
        driver=YTDriver(profile_dir=profile_dir, headless=True, verbose=True, use_virtual_display=False),
        puppetId=puppetId,
        actions=[],
        start_time=datetime.now(),
    )
    return puppet


def makedir(outputDir, d):
    dir = os.path.join(outputDir, d)
    if not os.path.exists(dir):
        os.makedirs(dir)
    return dir


def make_url(videoId):
    return 'https://youtube.com/watch?v=' + str(videoId)


def add_action(action, params=None):
    # Records every action the puppet takes with timestamp
    print(action, params)
    puppet['actions'].append(dict(action=action, params=params))


def get_homepage():
    homepage = puppet['driver'].get_homepage_recommendations(scroll_times=10)
    add_action('get_homepage_recommendations', [vid.videoId for vid in homepage])
    return homepage


def get_recommendations():
    recommendations = puppet['driver'].get_upnext_recommendations(topn=12)
    add_action('get_upnext_recommendations', [vid.videoId for vid in recommendations])
    return recommendations


def watch(video: Video, duration):
    driver = puppet['driver']
    try:
        driver.play(video, duration=duration)
    except VideoUnavailableException as e:
        print("Skipping unavailable video")
        pass
    add_action('watch', video.videoId)


def save_puppet():
    js = dict(
        puppet_id=puppet['puppetId'],
        start_time=puppet['start_time'],
        end_time=datetime.now(),
        duration=puppet['duration'],
        description=puppet['description'],
        actions=puppet['actions'],
        # harmful_watched=puppet['harmful_count'],
        # non_harmful_watched=puppet['harmless_count'],
        # actual_harmful_percentage=puppet['actual_harmful_percentage'],
        args=args
    )
    with open(os.path.join(makedir(args['outputDir'], 'puppets'), puppet['puppetId']), 'w') as f:
        json.dump(js, f, default=str, indent=4)


def train():
    get_homepage()
    add_action("training_start")

    # Create screenshots directory
    screenshots_dir = os.path.join(args['outputDir'], 'screenshots', args['puppetId'])
    if not os.path.exists(screenshots_dir):
        os.makedirs(screenshots_dir)

    # get list of videoIds
    training = args["training"]
    training_videos = [videoId for videoId in training if len(videoId) > 0]
    trainingN = int(args["trainingN"])
    # number of videos watched
    watched = 0

    last_video = None
    for videoId in training_videos:
        # watch until N videos have been watched
        if watched >= trainingN:
            break

        # Watch the video
        try:
            video = Video(None, make_url(videoId))
            watch(video, args["duration"])
            last_video = video
            watched += 1
        except VideoUnavailableException:
            continue
        except Exception as e:
            logger.exception(e)

    add_action("training_end")

    """ Get upnext recommendations after training """
    if last_video is not None:
        retry_upnext = 0
        # Take screenshot before getting recommendations
        puppet["driver"].save_screenshot(os.path.join(screenshots_dir, f"last_video_before_recs.png"))
        up_next = puppet["driver"].get_upnext_recommendations(topn=12)
        add_action("get_upnext_recommendations", [vid.videoId for vid in up_next])
    else:
        raise Exception("No video to get recommendations from {videoId}.")

    """ Get homepage recommendations after training """
    homepage = puppet["driver"].get_homepage_recommendations(scroll_times=4)
    # Take screenshot after first attempt
    puppet["driver"].save_screenshot(os.path.join(screenshots_dir, f"homepage_first_attempt.png"))
    add_action("get_homepage_recommendations", [vid.videoId for vid in homepage])


def test():
    # Refreash homepage 4 times before starting test
    # for _ in range(4):
    #     get_homepage()
    #     time.sleep(1)
    add_action("testing_start")
    get_homepage()
    # video = Video(None, make_url(args['testSeed']))
    # watch(video, 0)
    # get_recommendations()
    # for _ in range(20):
    #     watch(video, 0)
    #     r = get_recommendations()
    #     video = r[0]
    add_action("testing_end")

    # If we've watched any videos, use the last one for recommendations
    last_video_id = args['testSeed']
    if last_video_id:
        add_action("testing_start", last_video_id)

        # Get recommendations based on the last video
        try:
            # Ensure we're still on the last video's page
            video = Video(None, make_url(last_video_id))
            # Don't need to watch again, just get recommendations
            recommendations = get_recommendations()
            add_action("training_video_recommendations", [vid.videoId for vid in recommendations])
        except Exception as e:
            print(f"Error getting recommendations for last video: {e}")

    # Now get homepage recommendations (as a separate step)
    try:
        homepage_videos = get_homepage()
        add_action("post_training_homepage", [vid.videoId for vid in homepage_videos])
    except Exception as e:
        print(f"Error getting homepage after training: {e}")


def trainWatch():
    get_homepage()
    add_action("Watch_start")
    for videoId in args['intervention']:
        print("Loading video:", videoId)
        try:
            video = Video(None, make_url(videoId))
            watch(video, args['duration'])
            print("Video watched successfully")
        except VideoUnavailableException:
            print(f"Skipping unavailable video: {videoId}")
            continue  # Skip the current iteration and move to the next video
        except Exception as e:
            print(f"An unexpected error occurred while watching video {videoId}: {e}")
            continue  # Optionally, continue with the next video in case of any other unexpected error

        time.sleep(1)

    add_action("Watch_end")


def intervention():
    get_homepage()
    add_action("intervention_start")
    for videoId in args['intervention']:
        print("Loading video:", videoId)
        try:
            video = Video(None, make_url(videoId))
            watch(video, args['duration'])
            print("Video watched successfully")
        except VideoUnavailableException:
            print(f"Skipping unavailable video: {videoId}")
            continue  # Skip the current iteration and move to the next video
        except Exception as e:
            print(f"An unexpected error occurred while watching video {videoId}: {e}")
            continue  # Optionally, continue with the next video in case of any other unexpected error

    add_action("intervention_end")


def search_and_watch():
    search_term = 'fashion tips'  # Since we can't pass this as an attribute
    top_n = 10  # number of top videos to watch

    videos = puppet['driver'].search_videos(query=search_term)

    top_videos = videos[:top_n]  # Assuming search_videos returns a sorted list

    # Store these videos in an intervention-like attribute for consistency
    puppet['interventionVideos'] = [video.url for video in top_videos]

    for video in top_videos:
        print(f"Watching video: {video.url}")
        watch(video, args['duration'])

    # Additional logic for taking a screenshot, etc., would follow here


def load_video_pools():
    # Load harmful and non-harmful videos from csv files
    try:
        TRAINING_BASE = "data/training/"
        harmful_pool = pd.read_csv(os.path.join(TRAINING_BASE, 'harmful.csv'))
        # non_harmful_pool = pd.read_csv(os.path.join(TRAINING_BASE, 'non_harmful.csv'))
        print(f"Loaded {len(harmful_pool)} harmful videos.")
        return set(harmful_pool['videoId'].tolist())
    except Exception as e:
        print(f"Error loading video pools: {e}")


if __name__ == '__main__':
    # time.sleep(random.uniform(0, 3))
    args = json.loads(sys.argv[1])

    logging.basicConfig(format='%(asctime)s - %(levelname)s - %(message)s',
                        filename=f'/logs/{args["puppetId"]}', level=logging.INFO, filemode='w')
    logger = logging.getLogger(__name__)

    try:
        # conduct end-to-end experiment
        profile_dir = os.path.join(makedir(args["outputDir"], "profiles"), args["puppetId"])
        logger.info(f"Creating profile directory: {profile_dir}")
        logger.info("Successfully created profile directory")
        init_puppet(args["puppetId"], profile_dir)
        logger.info("Initialized sock puppet:", args["puppetId"])

        train()

        # finalize puppet
        puppet["driver"].close()
        puppet["steps"] = args["steps"]
        puppet["duration"] = args["duration"]
        puppet["description"] = args["description"]
        save_puppet()
        logger.info('sock puppet finished')
    except Exception as e:
        logger.exception(e)
        # puppet['steps'] = args['steps']
        # puppet['duration'] = args['duration']
        # puppet['description'] = args['description']
        # save_puppet()
